uuid = "6dc10dc7-15ba-423f-874a-4a446cd949c3"
name = "File Writer"
authors = ["Bob Swift"]
description = "This plugin adds a scripting function $writeline() to allow writing text to an output file."
api = ['3.0']
license = "GPL-2.0 or later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
long_description = """
This plugin adds a scripting function `$writeline()` to allow writing text to an output file.

Usage: **$writeline(file,text[,reset])**

This will write `text` (followed by a newline) to `file`. The text will be appended to the file
unless `reset` is set, in which case the file will be overwritten. If the destination `file` path
is not specified as an absolute path to the destination file (beginning with a Windows drive letter
and colon or path separator), then the path will be considered relative to the ***Destination
directory*** specified in Picard's **File Naming Options** settings. If the target path does not exist,
it will be created automatically.

***NOTE:*** The text will be written to the file with a character encoding of UTF-8.
"""
categories = [
    "scripting",
    "other",
]
homepage = "https://picard-plugins-user-guides.readthedocs.io/en/latest/file_writer/user_guide.html"
